version: '3.3'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  
  apollo-graphql-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rags:latest
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/app:cached
    ports:
      - 4000:4000
      
volumes:
  postgres: